pipeline:
  test:
    image: nextcloudci/android:android-28
    commands:
      # - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
      # - emulator -avd test -no-window &
      # - ./wait_for_emulator.sh
      # build app 
      - ./gradlew clean build

    environment:
      - ANDROID_TARGET=android-24
      - ANDROID_ABI=armeabi-v7a
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/opt/android-sdk-linux/tools/lib64/gles_mesa/
