pipeline:
  compile:
    image: nextcloudci/android:android-33
    commands:
      # build app and assemble APK
      - ./gradlew assemble

  test:
      image: nextcloudci/android:android-33
      privileged: true
      commands:
        - emulator -avd android-27 -no-window -no-audio &
        - ./wait_for_emulator.sh && ./gradlew :test_client:connectedDebugAndroidTest --info
      secrets: [ LOG_USERNAME, LOG_PASSWORD ]

  notify:
        image: drillster/drone-email
        host: $EMAIL_HOST
        port: 587
        username: $EMAIL_USERNAME
        password: $EMAIL_PASSWORD
        from: nextcloud-drone@kaminsky.me
        recipients_only: true
        recipients: [ $EMAIL_RECIPIENTS ]
        secrets: [ EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_RECIPIENTS, EMAIL_HOST ]
        when:
          event: push
          status: failure
          branch: master

services:
  server:
    image: nextcloudci/server:server-1

branches: master
