# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: "Garm"

on:
    pull_request:
        branches: [ master, stable-* ]

permissions:
    contents: read
    pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-24.04
        services:
            server:
                image: ${{ matrix.server == 'stable22' && 'ghcr.io/nextcloud/continuous-integration-shallow-server-php8.0:1' || 'ghcr.io/nextcloud/continuous-integration-shallow-server-php8.2:1' }}
                options: --name server
                ports:
                    - 80:80
        strategy:
            fail-fast: false
            matrix:
                server: [ stable22, stable33, master ]
                api-level: [ 29 ] # [ 21, 36 ]
        steps:
            -   uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            -   name: configure server
                run: |
                    sudo apt-get update && sudo apt-get install unzip cpu-checker qemu-kvm --yes
                    sudo chmod 666 /dev/kvm
                    docker cp .github/workflows/configServer.sh server:/tmp/
                    docker exec server chmod +x /tmp/configServer.sh
                    docker exec server /tmp/configServer.sh ${{ matrix.server }}
                    docker cp .github/workflows/configNC.sh server:/tmp/
                    docker exec server chmod +x /tmp/configNC.sh
                    docker exec --user www-data server /tmp/configNC.sh ${{ matrix.server }}
                    docker exec server /usr/local/bin/run.sh

            -   name: set up JDK 17
                uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
                with:
                    distribution: "temurin"
                    java-version: 17

            -   name: Enable KVM group perms
                run: |
                    echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                    sudo udevadm control --reload-rules
                    sudo udevadm trigger --name-match=kvm


            -   name: create AVD and generate snapshot for caching
                uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
                with:
                    api-level: ${{ matrix.api-level }}
                    force-avd-creation: false
                    arch: x86
                    sdcard-path-or-size: 100M
                    target: google_apis
                    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
                    script: echo "Generated AVD snapshot for caching."

            -   name: Configure gradle daemon
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties

            -   name: Build gplay
                run: |
                    sed -i s#https://server#http://10.0.2.2# gradle.properties
                    sed -i s"#1#5#" ./library/src/androidTest/java/com/owncloud/android/RetryTestRule.kt
                    ./gradlew assembleDebug

            -   name: wait and ping server
                run: |
                    while ! curl http://localhost/status.php 2>&1 | grep installed; do
                        echo "wait…"
                        sleep 5
                    done

            -   name: gplay
                uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
                with:
                    api-level: ${{ matrix.api-level }}
                    force-avd-creation: false
                    arch: x86
                    sdcard-path-or-size: 100M
                    target: google_apis
                    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
                    script: scripts/runTests.sh

            -   name: upload failing results
                if: ${{ failure() }}
                env:
                    LOG_USERNAME: ${{ secrets.LOG_USERNAME }}
                    LOG_PASSWORD: ${{ secrets.LOG_PASSWORD }}
                    GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                run: scripts/uploadReport.sh "${{ secrets.LOG_USERNAME }}"  "${{ secrets.LOG_PASSWORD }}"   ${{github.event.number}}    ${{ matrix.server }} "IT" ${{github.event.number}} "${{ secrets.GIT_USERNAME }}" "${{ secrets.GIT_TOKEN }}"
            -   name: Archive Espresso results
                uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
                if: ${{ always() }}
                with:
                    name: Report-${{ matrix.server }}-${{ matrix.api-level }}
                    path: app/build/reports
                    retention-days: 4
